# This is a basic workflow to help you get started with Actions

name: Convert-Roam-to-HTML

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
  schedule:
    -   cron: "0 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Gets the most recent release of a repository
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: dvargas92495
          repo: generate-roam-site-action
          excludes: prerelease, draft
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate HTML From Roam
        uses: dvargas92495/generate-roam-site-action@${{ keydb.outputs.release }}
        with:
          roam_username: ${{ secrets.ROAMRESEARCH_USER }}
          roam_password: ${{ secrets.ROAMRESEARCH_PASSWORD }}
          roam_graph: ${{ secrets.ROAMRESEARCH_DATABASE }}

      - name: cleanup
        run: |
            rm -r downloads
            mv -v out/* $GITHUB_WORKSPACE/src/
            cd $GITHUB_WORKSPACE

      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Automated snapshot
